### ISSUE TITLE
准备添加middleware文件夹

### ISSUE THREAD

**Issue by andycall** [wssgcg1213/RedApi2#5]
做一个middleware管理器， 然后插件管理器也做为一个中间件， 再通过插件管理器加载插件，其实也是变相的作为中间件管理。

**Comment by wssgcg1213** [comment]
恩 但是叫middleware这个名字是不是不妥 会跟express的中间件概念冲突

**Comment by wssgcg1213** [comment]
虽然的确是中间件  叫pluginAdapter 之类的

**Comment by andycall** [comment]
后来放common里面了😂
